# -*- coding: utf-8 -*-
"""calculadora_python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jxARJ9HE7-qks1hulDxpNVQdForxglTs
"""

n1 = int(input('Digite o primeiro número: '))
n2 = int(input('Digite o segundo número: '))
s = n1+n2
subtracao = n1-n2
multiplicacao = n1*n2
div = n1 / n2
resto_div = n1 % n2

print('{} + {} = {} '.format(n1, n2, s))
print('{} - {} = {} '.format(n1, n2, subtracao))
print('{} x {} = {} '.format(n1, n2, multiplicacao))
print('{} / {} = {} '.format(n1, n2, div))
print('{} % {} = {} '.format(n1, n2, resto_div))