# -*- coding: utf-8 -*-
"""exemplo_lab_prog_unit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mGecWAdO1dA6sD8nbJMXiJq0q5nqyd9m
"""

#Operações Aritméticas

x=8-4
x
print('O resultado dessa operação é igual a {}'.format(x))

#Imprimir string

y = "Eu amo programar"
y
print(y)

k = 3.90 - 2.00
k
print('O resultado dessa operação é igual a {}'.format(k))

#Tipo de dado classificado 

type(y)
type(k)
type(x)

#Comparação entre valores

x > 6

x > 15

#Erro de concatenação

v = "1"
q = 1
#print(v+q)

#Operação entre valores

v = 1.5
q = 1
print(v+q)

resultado = v+q

type(resultado)

#Comando if

num = int(input('Digite um número: '))
par = 0
impar = 0

if num % 2 == 0:

     par = par + 1
     print("PAR")
else:
     impar = impar + 1
     print("IMPAR")

l = list(range(5))
print(l)
l.append(5)
print(l)
l.insert(0,6)
print(l)
l.reverse()
print(l)
l.sort()
print(l)

#Comando range (Criação de listas)

l = list(range(10))
l
l[2:7]

l[3:6]

l[1:5]

#Comando slice (Criação de listas)
lista = list(range(10))
lista
l[2:7]
l[2:7:2]
l[1:4:6]
l[2:5:1]
